import type SendMessage from './Args/SendMessage';
import type SendPhoto from './Args/SendPhoto';
import type ChatPhoto from './Entities/ChatPhoto';
import type Message from './Entities/Message';
import type User from './Entities/User';
import type ForwardMessage from './Args/ForwardMessage';
import type SendMediaGroup from './Args/SendMediaGroup';
import type SendAudio from './Args/SendAudio';
import type SendDocument from './Args/SendDocument';
import type GetChatMember from './Args/GetChatMember';
import type ChatMember from './Entities/ChatMember';
import type Chat from './Entities/Chat';
import type File from './Entities/File';
import type SendSticker from './Args/SendSticker';
import type SendVideo from './Args/SendVideo';
import type SendVoice from './Args/SendVoice';
import type SendLocation from './Args/SendLocation';
import type EditMessageLiveLocation from './Args/EditMessageLiveLocation';
import type StopMessageLiveLocation from './Args/StopMessageLiveLocation';
import type SendVenue from './Args/SendVenue';
import type SendContact from './Args/SendContact';
import type SendPoll from './Args/SendPoll';
import type StopPoll from './Args/StopPoll';
import type Poll from './Entities/Poll';
import type SendChatAction from './Args/SendChatAction';
import type GetUserProfilePhotos from './Args/GetUserProfilePhotos';
import type UserProfilePhotos from './Entities/UserProfilePhotos';
import type KickChatMember from './Args/KickChatMember';
import type UnbanChatMember from './Args/UnbanChatMember';
import type AnswerCallbackQuery from './Args/AnswerCallbackQuery';
import type EditMessageText from './Args/EditMessageText';
import type EditMessageCaption from './Args/EditMessageCaption';
import type EditMessageReplyMarkup from './Args/EditMessageReplyMarkup';
import type AnswerInlineQuery from './Args/AnswerInlineQuery';
import type SendGame from './Args/SendGame';
import type SetGameScore from './Args/SetGameScore';
import type GetGameHighScores from './Args/GetGameHighScores';
import type GameHighScore from './Entities/GameHighScore';
import type GetUpdates from './Args/GetUpdates';
import type Update from './Entities/Update';
import type SetWebhook from './Args/SetWebhook';
import type WebhookInfo from './Entities/WebhookInfo';
import type DeleteMessage from './Args/DeleteMessage';
import type RestrictChatMember from './Args/RestrictChatMember';
import type PromoteChatMember from './Args/PromoteChatMember';
import type SetChatPhoto from './Args/SetChatPhoto';
import type SetChatTitle from './Args/SetChatTitle';
import type SetChatDescription from './Args/SetChatDescription';
import type PinChatMember from './Args/PinChatMember';
import type StickerSet from './Entities/StickerSet';
import type UploadStickerFile from './Args/UploadSticketFile';
import type CreateNewStickerSet from './Args/CreateNewStickerSet';
import type SetChatSticketSet from './Args/SetChatSticketSet';
import type AddSticketToSet from './Args/AddSticketToSet';
import type SetStickerPositionInSet from './Args/SetSticketPositionInSet';
import type SendInvoice from './Args/SendInvoice';
import type AnswerShippingQuery from './Args/AnswerShippingQuery';
import type AnswerPreCheckoutQuery from './Args/AnswerPreCheckoutQuery';
import type EditMessageMedia from './Args/EditMessageMedia';
import type SendAnimation from './Args/SendAnimation';

export type ApiMethods = {
  sendMessage: [SendMessage, Message];
  sendPhoto: [SendPhoto, ChatPhoto];
  getMe: [never, User];
  forwardMessage: [ForwardMessage, Message];
  sendMediaGroup: [SendMediaGroup, Message[]];
  sendAudio: [SendAudio, Message];
  sendDocument: [SendDocument, Message];
  getChatMembersCount: [number | string, number];
  getChatMember: [GetChatMember, ChatMember];
  getChat: [string | number, Chat];
  getChatAdministrators: [number | string, ChatMember[]];
  leaveChat: [number | string, boolean];
  getFile: [string, File];
  sendSticker: [SendSticker, Message];
  sendVideo: [SendVideo, Message];
  sendVoice: [SendVoice, Message];
  sendLocation: [SendLocation, Message];
  editMessageLiveLocation: [EditMessageLiveLocation, Message | boolean];
  stopMessageLiveLocation: [StopMessageLiveLocation, Message | boolean];
  sendVenue: [SendVenue, Message];
  sendContact: [SendContact, Message];
  sendPoll: [SendPoll, Message];
  stopPoll: [StopPoll, Poll];
  sendChatAction: [SendChatAction, boolean];
  getUserProfilePhotos: [GetUserProfilePhotos, UserProfilePhotos];
  kickChatMember: [KickChatMember, boolean];
  unbanChatMember: [UnbanChatMember, boolean];
  answerCallbackQuery: [AnswerCallbackQuery, boolean];
  editMessageText: [EditMessageText, Message | boolean];
  editMessageCaption: [EditMessageCaption, Message | boolean];
  editMessageReplyMarkup: [EditMessageReplyMarkup, Message | boolean];
  answerInlineQuery: [AnswerInlineQuery, boolean];
  sendGame: [SendGame, Message];
  setGameScore: [SetGameScore, Message | boolean];
  getGameHighScores: [GetGameHighScores, GameHighScore[]];
  getUpdates: [GetUpdates, Update[]];
  setWebhook: [SetWebhook, boolean];
  deleteWebhook: [never, boolean];
  getWebhookInfo: [never, WebhookInfo];
  deleteMessage: [DeleteMessage, boolean];
  restrictChatMember: [RestrictChatMember, boolean];
  promoteChatMember: [PromoteChatMember, boolean];
  exportChatInviteLink: [number | string, string];
  setChatPhoto: [SetChatPhoto, boolean];
  deleteChatPhoto: [number | string, boolean];
  setChatTitle: [SetChatTitle, boolean];
  setChatDescription: [SetChatDescription, boolean];
  pinChatMessage: [PinChatMember, boolean];
  unpinChatMessage: [number | string, boolean];
  getStickerSet: [string, StickerSet];
  uploadStickerFile: [UploadStickerFile, File];
  createNewStickerSet: [CreateNewStickerSet, boolean];
  setChatStickerSet: [SetChatSticketSet, boolean];
  deleteChatStickerSet: [number | string, boolean];
  addStickerToSet: [AddSticketToSet, boolean];
  setStickerPositionInSet: [SetStickerPositionInSet, boolean];
  sendInvoice: [SendInvoice, Message];
  answerShippingQuery: [AnswerShippingQuery, boolean];
  answerPreCheckoutQuery: [AnswerPreCheckoutQuery, boolean];
  deleteStickerFromSet: [string, boolean];
  editMessageMedia: [EditMessageMedia, Message];
  sendAnimation: [SendAnimation, Message];
};
