import { Chat } from "./Chat";
import { PhotoSize } from "./PhotoSize";
import { Sticker } from "./Sticker";
import { User } from "./User";

import { Audio } from "./Audio";
import { Contact } from "./Contact";
import { Game } from "./Game";
import { Invoice } from "./Invoice";
import { MessageEntity } from "./MessageEntity";
import { SuccessfulPayment } from "./SuccessfulPayment";
import { Venue } from "./Venue";
import { Video } from "./Video";
import { VideoNote } from "./VideoNote";
import { Voice } from "./Voice";

export interface Message {
  message_id: number;
  from: User;
  date: number;
  chat: Chat;
  forward_from: User;
  forward_from_chat: Chat;
  forward_from_message_id: number;
  forward_signature: string;
  forward_date: number;
  reply_to_message: Message;
  edit_date: number;
  media_group_id: string;
  author_signature: string;
  text: string;
  entities: MessageEntity[];
  caption_entities: MessageEntity[];
  audio: Audio;
  document: Document;
  game: Game;
  photo: PhotoSize[];
  sticker: Sticker;
  video: Video;
  voice: Voice;
  video_note: VideoNote;
  caption: string;
  contact: Contact;
  location: Location;
  venue: Venue;
  new_chat_members: User[];
  left_chat_member: User;
  new_chat_title: string;
  new_chat_photo: PhotoSize[];
  delete_chat_photo: boolean;
  group_chat_created: boolean;
  supergroup_chat_created: boolean;
  channel_chat_created: boolean;
  migrate_to_chat_id: number;
  migrate_from_chat_id: number;
  pinned_message: Message;
  invoice: Invoice;
  successful_payment: SuccessfulPayment;
}
