import { IChat as Chat } from "./IChat";
import { IPhotoSize as PhotoSize } from "./IPhotoSize";
import { ISticker as Sticker } from "./ISticker";
import { IUser as User } from "./IUser";

import { IAudio as Audio } from "./IAudio";
import { IContact as Contact } from "./IContact";
import { IGame as Game } from "./IGame";
import { IInvoice as Invoice } from "./IInvoice";
import { IMessageEntity as MessageEntity } from "./IMessageEntity";
import { ISuccessfulPayment as SuccessfulPayment } from "./ISuccessfulPayment";
import { IVenue as Venue } from "./IVenue";
import { IVideo as Video } from "./IVideo";
import { IVideoNote as VideoNote } from "./IVideoNote";
import { IVoice as Voice } from "./IVoice";

export interface IMessage {
  message_id: number;
  from: User;
  date: number;
  chat: Chat;
  forward_from: User;
  forward_from_chat: Chat;
  forward_from_message_id: number;
  forward_signature: string;
  forward_date: number;
  reply_to_message: IMessage;
  edit_date: number;
  media_group_id: string;
  author_signature: string;
  text: string;
  entities: MessageEntity[];
  caption_entities: MessageEntity[];
  audio: Audio;
  document: Document;
  game: Game;
  photo: PhotoSize[];
  sticker: Sticker;
  video: Video;
  voice: Voice;
  video_note: VideoNote;
  caption: string;
  contact: Contact;
  location: Location;
  venue: Venue;
  new_chat_members: User[];
  left_chat_member: User;
  new_chat_title: string;
  new_chat_photo: PhotoSize[];
  delete_chat_photo: boolean;
  group_chat_created: boolean;
  supergroup_chat_created: boolean;
  channel_chat_created: boolean;
  migrate_to_chat_id: number;
  migrate_from_chat_id: number;
  pinned_message: IMessage;
  invoice: Invoice;
  successful_payment: SuccessfulPayment;
}
